name: Deploy front
 
on:
  push:
    branches:
      - master
    paths:
      - 'chousei-front/src/**'
 
jobs:
  build:
 
    runs-on: ubuntu-18.04
    timeout-minutes: 300
 
    steps:
    - uses: actions/checkout@v1    
 
    - name: Build and Push
      env:
        ACCESS_TOKEN:  ${{ secrets.CHOUSEI_FRONT_ACCESS_TOKEN }}
      run: |
        git clone https://x-access-token:${ACCESS_TOKEN}@github.com/Taita-ldt/Taita-ldt.github.io.git
        git config --global user.email "chousei@github.io"
        git config --global user.name "chousei"
        docker build -t chousei-front .
        docker run --name chousei-front -d chousei-front
        docker cp chousei-front:/usr/share/nginx/html/. ./Taita-ldt.github.io
        cd Taita-ldt.github.io
        git add .
        git commit -m "Deploy $GITHUB_SHA by GitHub Actions"
        git push https://x-access-token:${ACCESS_TOKEN}@github.com/Taita-ldt/Taita-ldt.github.io.git master
      working-directory: ./chousei-front

    - name: failure
      if: failure()
      uses: pullreminders/slack-action@master
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        # "channel"にSlackチャンネルIDを代入
        args: '{\"channel\":\"C010ZGUAGG5\", \"text\":\":sleeping_accommodation:フロントデプロイ失敗:sleeping_accommodation:\nhttps://github.com/Taita-ldt/chosei/actions/runs/${{ github.run_id }}\"}'

    - name: success
      uses: pullreminders/slack-action@master
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        # "channel"にSlackチャンネルIDを代入
        args: '{\"channel\":\"C010ZGUAGG5\", \"text\":\":person_doing_cartwheel:フロントデプロイ成功:person_doing_cartwheel:\nhttps://github.com/Taita-ldt/chosei/actions/runs/${{ github.run_id }}\nhttps://taita-ldt.github.io/#/\"}'